export const stations = [
  {
    id: "1",
    name: "ChargeFast Central",
    address: "123 Green Street, New Delhi",
    distance: 0.5,
    rating: 4.8,
    reviews: 234,
    availableChargers: 8,
    totalChargers: 12,
    priceMin: 5,
    priceMax: 7,
    chargerTypes: ["Type 2", "CCS", "AC"],
    amenities: ["Cafe", "Restroom", "Food Court", "WiFi"],
    open: "24/7",
    image:
      "https://images.unsplash.com/photo-1617788138017-80ad40651399?auto=format&fit=crop&w=1200&q=80",
    lat: 28.6145,
    lng: 77.2089,
    occupancy: 66,
    waitTime: "12 min",
  },
  {
    id: "2",
    name: "PowerHub Station",
    address: "MG Road, Gurgaon",
    distance: 1.2,
    rating: 4.5,
    reviews: 118,
    availableChargers: 3,
    totalChargers: 8,
    priceMin: 6,
    priceMax: 8,
    chargerTypes: ["AC", "DC"],
    amenities: ["WiFi", "Lounge", "Restroom"],
    open: "6 AM - 12 AM",
    image:
      "https://images.unsplash.com/photo-1593941707882-a5bba14938c7?auto=format&fit=crop&w=1200&q=80",
    lat: 28.4595,
    lng: 77.0266,
    occupancy: 38,
    waitTime: "5 min",
  },
  {
    id: "3",
    name: "EcoVolt Plaza",
    address: "Noida Sector 62",
    distance: 2.7,
    rating: 4.7,
    reviews: 176,
    availableChargers: 5,
    totalChargers: 10,
    priceMin: 4,
    priceMax: 6,
    chargerTypes: ["CCS", "Type 2", "CHAdeMO"],
    amenities: ["Cafe", "Valet", "Food Court"],
    open: "24/7",
    image:
      "https://images.unsplash.com/photo-1609521263047-f8f205293f24?auto=format&fit=crop&w=1200&q=80",
    lat: 28.6328,
    lng: 77.2197,
    occupancy: 50,
    waitTime: "18 min",
  },
];

export const bookings = [
  {
    id: "b1",
    stationId: "1",
    stationName: "ChargeFast Central",
    charger: "Charger #2 (50 kW DC)",
    status: "Active",
    progress: 45,
    startTime: "2:30 PM",
    endTime: "3:15 PM",
    price: 150,
    date: "Today",
    vehicleName: "Tata Nexon EV",
    vehicleNumber: "DL01AB1234",
  },
  {
    id: "b2",
    stationId: "2",
    stationName: "PowerHub Station",
    charger: "Charger #1 (7 kW AC)",
    status: "Upcoming",
    progress: 0,
    startTime: "3:00 PM",
    endTime: "4:30 PM",
    price: 90,
    date: "Tomorrow",
    vehicleName: "MG ZS EV",
    vehicleNumber: "HR26CD5678",
  },
  {
    id: "b3",
    stationId: "3",
    stationName: "EcoVolt Plaza",
    charger: "Charger #6 (25 kW CCS)",
    status: "Past",
    progress: 100,
    startTime: "1:20 PM",
    endTime: "2:40 PM",
    price: 225,
    date: "2 weeks ago",
    vehicleName: "Hyundai Kona Electric",
    vehicleNumber: "UP16EF2468",
  },
];

export const notifications = [
  {
    id: "n1",
    category: "Bookings",
    title: "Booking confirmed",
    message: "Charger #2 is reserved for your 3:00 PM session at ChargeFast Central.",
    time: "2 min ago",
    read: false,
  },
  {
    id: "n2",
    category: "System",
    title: "Car fully charged",
    message: "Your booking ended automatically. 42 kWh charged and Rs 210 paid.",
    time: "18 min ago",
    read: false,
  },
  {
    id: "n3",
    category: "Promotions",
    title: "50% off at PowerHub",
    message: "Limited time weekday offer for fast charging between 2 PM and 5 PM.",
    time: "1 hour ago",
    read: true,
  },
];
